typography_spectrum: 0.7567390184849501
content_rating:
  adult: false
color:
  brandStrength: 0.08782367827370763
  lightness: 0.5005922170821577
  saturation: 0.4785632265266031
  rhythmicContrast: 0.599784160265699
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
layout_spectrum: 0.9511729425285012
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1ccaedb6-32c0-4c65-a414-f12a6d9a009e.png
name: Rowhouse Spirits
title: 'Hand Crafted, Small Batch.'
description: One guy making exceptional spirits - 100 bottles at a time.
